### ISSUE TITLE
Link to installer pages for SCT and shimming-toolbox

### ISSUE THREAD

**Issue by namgo** [4rnaudB/spinalcord-signal-recovery#11]
Following up on installation issues I'm having as someone who's not super familiar with NeuroPoly's science projects, it might be a good idea to link to SCT and shimming-toolbox installation pages or even a summary of them in the readme?

From a reproducible science perspective, would it make sense to add something like:

> These scripts require shimming-toolbox, spinalcordtoolbox and FSL
> To install shimming-toolbox:
```
git clone -b 1.1 https://github.com/shimming-toolbox/shimming-toolbox/ ~/shimming-toolbox/
cd ~/shimming-toolbox/
make install
```

In place of
> Download [Shimming Toolbox's v1.1](https://github.com/shimming-toolbox/shimming-toolbox/releases/tag/1.1)

(and the same for SCT)

This might help people like me who aren't familiar with the installation procedure for NeuroPoly projects.

FSL is a bit different because to my knowledge it doesn't track versions - and the linked installer page is pretty clear.

**Comment by 4rnaudB** [comment]
@namgo  Changed the README

**Comment by namgo** [comment]
Nice!! That looks really good :)
